/**
 * Centralized Cloudinary CDN Asset Mapping
 * Resolves local image paths to Cloudinary CDN URLs seamlessly.
 */

export const CLOUDINARY_ASSETS = {
  // 1. Signature Shirts
  'linenshirt_lqdcpp.jpg': 'https://res.cloudinary.com/qrhgjdrs/image/upload/v1789314781/linenshirt_lqdcpp.jpg',
  "https://res.cloudinary.com/qrhgjdrs/image/upload/v1789314781/linenshirt_lqdcpp.jpg": 'https://res.cloudinary.com/qrhgjdrs/image/upload/v1789314781/linenshirt_lqdcpp.jpg',
  "https://res.cloudinary.com/qrhgjdrs/image/upload/v1789314781/linenshirt_lqdcpp.jpg": 'https://res.cloudinary.com/qrhgjdrs/image/upload/v1789314781/linenshirt_lqdcpp.jpg',
  "https://res.cloudinary.com/qrhgjdrs/image/upload/v1789314781/linenshirt_lqdcpp.jpg": 'https://res.cloudinary.com/qrhgjdrs/image/upload/v1789314781/linenshirt_lqdcpp.jpg',
  'half_y2ettu.jpg': 'https://res.cloudinary.com/qrhgjdrs/image/upload/v1789315007/half_y2ettu.jpg',
  "https://res.cloudinary.com/qrhgjdrs/image/upload/v1789315007/half_y2ettu.jpg": 'https://res.cloudinary.com/qrhgjdrs/image/upload/v1789315007/half_y2ettu.jpg',
  'strip_tx7ml9.jpg': 'https://res.cloudinary.com/qrhgjdrs/image/upload/v1789315007/strip_tx7ml9.jpg',
  "https://res.cloudinary.com/qrhgjdrs/image/upload/v1789315007/strip_tx7ml9.jpg": 'https://res.cloudinary.com/qrhgjdrs/image/upload/v1789315007/strip_tx7ml9.jpg',
  'brown_qpsytq.jpg': 'https://res.cloudinary.com/qrhgjdrs/image/upload/v1789315007/brown_qpsytq.jpg',
  "https://res.cloudinary.com/qrhgjdrs/image/upload/v1789315007/brown_qpsytq.jpg": 'https://res.cloudinary.com/qrhgjdrs/image/upload/v1789315007/brown_qpsytq.jpg',

  // 2. Women\'s Tees & Tops
  "https://res.cloudinary.com/qrhgjdrs/image/upload/v1789393808/women-tee-la-varsity-polo_lbfhj5.png": 'https://res.cloudinary.com/qrhgjdrs/image/upload/v1789393808/women-tee-la-varsity-polo_lbfhj5.png',
  "https://res.cloudinary.com/qrhgjdrs/image/upload/v1789393808/women-tee-la-varsity-polo_lbfhj5.png": 'https://res.cloudinary.com/qrhgjdrs/image/upload/v1789393808/women-tee-la-varsity-polo_lbfhj5.png',
  "https://res.cloudinary.com/qrhgjdrs/image/upload/v1789393804/women-tee-beardless-jersey_pk9fqt.png": 'https://res.cloudinary.com/qrhgjdrs/image/upload/v1789393804/women-tee-beardless-jersey_pk9fqt.png',
  "https://res.cloudinary.com/qrhgjdrs/image/upload/v1789393804/women-tee-beardless-jersey_pk9fqt.png": 'https://res.cloudinary.com/qrhgjdrs/image/upload/v1789393804/women-tee-beardless-jersey_pk9fqt.png',
  "https://res.cloudinary.com/qrhgjdrs/image/upload/v1789393804/women-tee-contrast-collar-polo_u3ukva.png": 'https://res.cloudinary.com/qrhgjdrs/image/upload/v1789393804/women-tee-contrast-collar-polo_u3ukva.png',
  "https://res.cloudinary.com/qrhgjdrs/image/upload/v1789393804/women-tee-contrast-collar-polo_u3ukva.png": 'https://res.cloudinary.com/qrhgjdrs/image/upload/v1789393804/women-tee-contrast-collar-polo_u3ukva.png',
  "https://res.cloudinary.com/qrhgjdrs/image/upload/v1789393806/women-tee-milan-striped-knit_h2vrgy.png": 'https://res.cloudinary.com/qrhgjdrs/image/upload/v1789393806/women-tee-milan-striped-knit_h2vrgy.png',
  "https://res.cloudinary.com/qrhgjdrs/image/upload/v1789393806/women-tee-milan-striped-knit_h2vrgy.png": 'https://res.cloudinary.com/qrhgjdrs/image/upload/v1789393806/women-tee-milan-striped-knit_h2vrgy.png',
  "https://res.cloudinary.com/qrhgjdrs/image/upload/v1789393806/women-tee-block-stripe-polo_woq63u.png": 'https://res.cloudinary.com/qrhgjdrs/image/upload/v1789393806/women-tee-block-stripe-polo_woq63u.png',
  "https://res.cloudinary.com/qrhgjdrs/image/upload/v1789393806/women-tee-block-stripe-polo_woq63u.png": 'https://res.cloudinary.com/qrhgjdrs/image/upload/v1789393806/women-tee-block-stripe-polo_woq63u.png',
  "https://res.cloudinary.com/qrhgjdrs/image/upload/v1789393806/women-tees-hanger-hero_wa5mfw.jpg": 'https://res.cloudinary.com/qrhgjdrs/image/upload/v1789393806/women-tees-hanger-hero_wa5mfw.jpg',
  "https://res.cloudinary.com/qrhgjdrs/image/upload/v1789393806/women-tees-hanger-hero_wa5mfw.jpg": 'https://res.cloudinary.com/qrhgjdrs/image/upload/v1789393806/women-tees-hanger-hero_wa5mfw.jpg',

  // 3. Women\'s Shirts & Cropped Blouses
  "https://res.cloudinary.com/qrhgjdrs/image/upload/v1789393804/women-plaid-crop-model_ui5xut.png": 'https://res.cloudinary.com/qrhgjdrs/image/upload/v1789393804/women-plaid-crop-model_ui5xut.png',
  "https://res.cloudinary.com/qrhgjdrs/image/upload/v1789393804/women-plaid-crop-model_ui5xut.png": 'https://res.cloudinary.com/qrhgjdrs/image/upload/v1789393804/women-plaid-crop-model_ui5xut.png',
  "https://res.cloudinary.com/qrhgjdrs/image/upload/v1789393802/women-shirt-crinkle-blue_gebghj.png": 'https://res.cloudinary.com/qrhgjdrs/image/upload/v1789393802/women-shirt-crinkle-blue_gebghj.png',
  "https://res.cloudinary.com/qrhgjdrs/image/upload/v1789393802/women-shirt-crinkle-blue_gebghj.png": 'https://res.cloudinary.com/qrhgjdrs/image/upload/v1789393802/women-shirt-crinkle-blue_gebghj.png',
  "https://res.cloudinary.com/qrhgjdrs/image/upload/v1789393802/women-shirt-noir-pinstripe_p3skaw.png": 'https://res.cloudinary.com/qrhgjdrs/image/upload/v1789393802/women-shirt-noir-pinstripe_p3skaw.png',
  "https://res.cloudinary.com/qrhgjdrs/image/upload/v1789393802/women-shirt-noir-pinstripe_p3skaw.png": 'https://res.cloudinary.com/qrhgjdrs/image/upload/v1789393802/women-shirt-noir-pinstripe_p3skaw.png',
  "https://res.cloudinary.com/qrhgjdrs/image/upload/v1789393802/women-shirt-sage-pinstripe_p9ql6o.png": 'https://res.cloudinary.com/qrhgjdrs/image/upload/v1789393802/women-shirt-sage-pinstripe_p9ql6o.png',
  "https://res.cloudinary.com/qrhgjdrs/image/upload/v1789393802/women-shirt-sage-pinstripe_p9ql6o.png": 'https://res.cloudinary.com/qrhgjdrs/image/upload/v1789393802/women-shirt-sage-pinstripe_p9ql6o.png',

  // 4. Women\'s Pants & Denim
  "https://res.cloudinary.com/qrhgjdrs/image/upload/v1789393805/women-pants-indigo-horseshoe_v2akiv.png": 'https://res.cloudinary.com/qrhgjdrs/image/upload/v1789393805/women-pants-indigo-horseshoe_v2akiv.png',
  "https://res.cloudinary.com/qrhgjdrs/image/upload/v1789393805/women-pants-indigo-horseshoe_v2akiv.png": 'https://res.cloudinary.com/qrhgjdrs/image/upload/v1789393805/women-pants-indigo-horseshoe_v2akiv.png',
  "https://res.cloudinary.com/qrhgjdrs/image/upload/v1789393798/women-pants-white-palazzo_xgiwtz.png": 'https://res.cloudinary.com/qrhgjdrs/image/upload/v1789393798/women-pants-white-palazzo_xgiwtz.png',
  "https://res.cloudinary.com/qrhgjdrs/image/upload/v1789393798/women-pants-white-palazzo_xgiwtz.png": 'https://res.cloudinary.com/qrhgjdrs/image/upload/v1789393798/women-pants-white-palazzo_xgiwtz.png',
  "https://res.cloudinary.com/qrhgjdrs/image/upload/v1789393797/women-pants-black-flare_pxg505.png": 'https://res.cloudinary.com/qrhgjdrs/image/upload/v1789393797/women-pants-black-flare_pxg505.png',
  "https://res.cloudinary.com/qrhgjdrs/image/upload/v1789393797/women-pants-black-flare_pxg505.png": 'https://res.cloudinary.com/qrhgjdrs/image/upload/v1789393797/women-pants-black-flare_pxg505.png',
  "https://res.cloudinary.com/qrhgjdrs/image/upload/v1789393798/women-pants-sculpt-flare-black_qbhy4h.png": 'https://res.cloudinary.com/qrhgjdrs/image/upload/v1789393798/women-pants-sculpt-flare-black_qbhy4h.png',
  "https://res.cloudinary.com/qrhgjdrs/image/upload/v1789393798/women-pants-sculpt-flare-black_qbhy4h.png": 'https://res.cloudinary.com/qrhgjdrs/image/upload/v1789393798/women-pants-sculpt-flare-black_qbhy4h.png',
  "https://res.cloudinary.com/qrhgjdrs/image/upload/v1789393795/women-pants-charcoal-horseshoe_t80ftv.png": 'https://res.cloudinary.com/qrhgjdrs/image/upload/v1789393795/women-pants-charcoal-horseshoe_t80ftv.png',
  "https://res.cloudinary.com/qrhgjdrs/image/upload/v1789393795/women-pants-charcoal-horseshoe_t80ftv.png": 'https://res.cloudinary.com/qrhgjdrs/image/upload/v1789393795/women-pants-charcoal-horseshoe_t80ftv.png',
  "https://res.cloudinary.com/qrhgjdrs/image/upload/v1789393794/women-pants-black-corset_jtkcjw.png": 'https://res.cloudinary.com/qrhgjdrs/image/upload/v1789393794/women-pants-black-corset_jtkcjw.png',
  "https://res.cloudinary.com/qrhgjdrs/image/upload/v1789393794/women-pants-black-corset_jtkcjw.png": 'https://res.cloudinary.com/qrhgjdrs/image/upload/v1789393794/women-pants-black-corset_jtkcjw.png',
  "https://res.cloudinary.com/qrhgjdrs/image/upload/v1789393796/women-pants-hanger-hero_ngr7mb.jpg": 'https://res.cloudinary.com/qrhgjdrs/image/upload/v1789393796/women-pants-hanger-hero_ngr7mb.jpg',
  "https://res.cloudinary.com/qrhgjdrs/image/upload/v1789393796/women-pants-hanger-hero_ngr7mb.jpg": 'https://res.cloudinary.com/qrhgjdrs/image/upload/v1789393796/women-pants-hanger-hero_ngr7mb.jpg',

  // 5. Women\'s Combos & Varsity
  "https://res.cloudinary.com/qrhgjdrs/image/upload/v1789393793/women-combo-denim-corset_t0tn2e.png": 'https://res.cloudinary.com/qrhgjdrs/image/upload/v1789393793/women-combo-denim-corset_t0tn2e.png',
  "https://res.cloudinary.com/qrhgjdrs/image/upload/v1789393793/women-combo-denim-corset_t0tn2e.png": 'https://res.cloudinary.com/qrhgjdrs/image/upload/v1789393793/women-combo-denim-corset_t0tn2e.png',
  "https://res.cloudinary.com/qrhgjdrs/image/upload/v1789393792/women-combo-lace-corset_z2aboy.png": 'https://res.cloudinary.com/qrhgjdrs/image/upload/v1789393792/women-combo-lace-corset_z2aboy.png',
  "https://res.cloudinary.com/qrhgjdrs/image/upload/v1789393792/women-combo-lace-corset_z2aboy.png": 'https://res.cloudinary.com/qrhgjdrs/image/upload/v1789393792/women-combo-lace-corset_z2aboy.png',
  "https://res.cloudinary.com/qrhgjdrs/image/upload/v1789393793/women-navy-ny23-cutout_dx47sj.png": 'https://res.cloudinary.com/qrhgjdrs/image/upload/v1789393793/women-navy-ny23-cutout_dx47sj.png',
  "https://res.cloudinary.com/qrhgjdrs/image/upload/v1789393793/women-navy-ny23-cutout_dx47sj.png": 'https://res.cloudinary.com/qrhgjdrs/image/upload/v1789393793/women-navy-ny23-cutout_dx47sj.png',
  "https://res.cloudinary.com/qrhgjdrs/image/upload/v1789393794/women-navy-ny23-model_ctrf7l.jpg": 'https://res.cloudinary.com/qrhgjdrs/image/upload/v1789393794/women-navy-ny23-model_ctrf7l.jpg',
  "https://res.cloudinary.com/qrhgjdrs/image/upload/v1789393794/women-navy-ny23-model_ctrf7l.jpg": 'https://res.cloudinary.com/qrhgjdrs/image/upload/v1789393794/women-navy-ny23-model_ctrf7l.jpg',

  // 6. Footer & Brand Assets
  "https://res.cloudinary.com/qrhgjdrs/image/upload/v1789393807/zudio-footer-banner_fzpsmb.webp": 'https://res.cloudinary.com/qrhgjdrs/image/upload/v1789393807/zudio-footer-banner_fzpsmb.webp',
  "https://res.cloudinary.com/qrhgjdrs/image/upload/v1789393807/zudio-footer-banner_fzpsmb.webp": 'https://res.cloudinary.com/qrhgjdrs/image/upload/v1789393807/zudio-footer-banner_fzpsmb.webp',
  "https://res.cloudinary.com/qrhgjdrs/image/upload/v1789393807/zudio-footer-banner_fzpsmb.webp": 'https://res.cloudinary.com/qrhgjdrs/image/upload/v1789393807/zudio-footer-banner_fzpsmb.webp',
  "https://res.cloudinary.com/qrhgjdrs/image/upload/v1789393807/zudio-footer-banner_fzpsmb.webp": 'https://res.cloudinary.com/qrhgjdrs/image/upload/v1789393807/zudio-footer-banner_fzpsmb.webp',
  "https://res.cloudinary.com/qrhgjdrs/image/upload/v1789393807/zudio-footer-banner_fzpsmb.webp": 'https://res.cloudinary.com/qrhgjdrs/image/upload/v1789393807/zudio-footer-banner_fzpsmb.webp',
  "https://res.cloudinary.com/qrhgjdrs/image/upload/v1789393807/zudio-footer-banner_fzpsmb.webp": 'https://res.cloudinary.com/qrhgjdrs/image/upload/v1789393807/zudio-footer-banner_fzpsmb.webp'

  'women-combo-lace-corset.png': 'https://res.cloudinary.com/qrhgjdrs/image/upload/v1789393792/women-combo-lace-corset_z2aboy.png',
  '/women-combo-lace-corset.png': 'https://res.cloudinary.com/qrhgjdrs/image/upload/v1789393792/women-combo-lace-corset_z2aboy.png',
  'women-mocha-ny-cutout.png': 'https://res.cloudinary.com/qrhgjdrs/image/upload/v1789393795/women-mocha-ny-cutout_nidkiz.png',
  '/women-mocha-ny-cutout.png': 'https://res.cloudinary.com/qrhgjdrs/image/upload/v1789393795/women-mocha-ny-cutout_nidkiz.png',
  'women-combo-pink-corduroy.png': 'https://res.cloudinary.com/qrhgjdrs/image/upload/v1789393792/women-combo-pink-corduroy_mbiouw.png',
  '/women-combo-pink-corduroy.png': 'https://res.cloudinary.com/qrhgjdrs/image/upload/v1789393792/women-combo-pink-corduroy_mbiouw.png',
  'women-combos-hanger-hero.jpg': 'https://res.cloudinary.com/qrhgjdrs/image/upload/v1789393792/women-combos-hanger-hero_c82mv0.jpg',
  '/women-combos-hanger-hero.jpg': 'https://res.cloudinary.com/qrhgjdrs/image/upload/v1789393792/women-combos-hanger-hero_c82mv0.jpg',
  'streetwear-cutout.png': 'https://res.cloudinary.com/qrhgjdrs/image/upload/v1789393791/streetwear-cutout_pu0nq7.png',
  '/streetwear-cutout.png': 'https://res.cloudinary.com/qrhgjdrs/image/upload/v1789393791/streetwear-cutout_pu0nq7.png',
  'women-combo-brown-corduroy.png': 'https://res.cloudinary.com/qrhgjdrs/image/upload/v1789393789/women-combo-brown-corduroy_derg0r.png',
  '/women-combo-brown-corduroy.png': 'https://res.cloudinary.com/qrhgjdrs/image/upload/v1789393789/women-combo-brown-corduroy_derg0r.png',
  'white-poplin-model.png': 'https://res.cloudinary.com/qrhgjdrs/image/upload/v1789393789/white-poplin-model_nvdjsa.png',
  '/white-poplin-model.png': 'https://res.cloudinary.com/qrhgjdrs/image/upload/v1789393789/white-poplin-model_nvdjsa.png',
  'streetwear-model.png': 'https://res.cloudinary.com/qrhgjdrs/image/upload/v1789393789/streetwear-model_ow6jj5.png',
  '/streetwear-model.png': 'https://res.cloudinary.com/qrhgjdrs/image/upload/v1789393789/streetwear-model_ow6jj5.png',
  'white-poplin-cutout.png': 'https://res.cloudinary.com/qrhgjdrs/image/upload/v1789393788/white-poplin-cutout_f4zcld.png',
  '/white-poplin-cutout.png': 'https://res.cloudinary.com/qrhgjdrs/image/upload/v1789393788/white-poplin-cutout_f4zcld.png',
  'sand-denim-model.png': 'https://res.cloudinary.com/qrhgjdrs/image/upload/v1789393786/sand-denim-model_jo9mrm.png',
  '/sand-denim-model.png': 'https://res.cloudinary.com/qrhgjdrs/image/upload/v1789393786/sand-denim-model_jo9mrm.png',
  'sand-denim-cutout.png': 'https://res.cloudinary.com/qrhgjdrs/image/upload/v1789393785/sand-denim-cutout_hfcqyg.png',
  '/sand-denim-cutout.png': 'https://res.cloudinary.com/qrhgjdrs/image/upload/v1789393785/sand-denim-cutout_hfcqyg.png',
  'paris-striped-cutout.png': 'https://res.cloudinary.com/qrhgjdrs/image/upload/v1789393785/paris-striped-cutout_n8cibd.png',
  '/paris-striped-cutout.png': 'https://res.cloudinary.com/qrhgjdrs/image/upload/v1789393785/paris-striped-cutout_n8cibd.png',

  'navy-crewneck-model.png': 'https://res.cloudinary.com/qrhgjdrs/image/upload/v1789393782/navy-crewneck-model_cigwed.png',
  '/navy-crewneck-model.png': 'https://res.cloudinary.com/qrhgjdrs/image/upload/v1789393782/navy-crewneck-model_cigwed.png',
  'paris-striped-model.png': 'https://res.cloudinary.com/qrhgjdrs/image/upload/v1789393783/paris-striped-model_kgyxxs.png',
  '/paris-striped-model.png': 'https://res.cloudinary.com/qrhgjdrs/image/upload/v1789393783/paris-striped-model_kgyxxs.png',
  'shirt-strip.jpg': 'https://res.cloudinary.com/qrhgjdrs/image/upload/v1789393785/shirt-strip_hnem9t.jpg',
  '/shirt-strip.jpg': 'https://res.cloudinary.com/qrhgjdrs/image/upload/v1789393785/shirt-strip_hnem9t.jpg',
  'men-tee-luffy-anime.png': 'https://res.cloudinary.com/qrhgjdrs/image/upload/v1789393782/men-tee-luffy-anime_merfml.png',
  '/men-tee-luffy-anime.png': 'https://res.cloudinary.com/qrhgjdrs/image/upload/v1789393782/men-tee-luffy-anime_merfml.png',
  'men-tee-stripe-knit.png': 'https://res.cloudinary.com/qrhgjdrs/image/upload/v1789393782/men-tee-stripe-knit_ms8ipb.png',
  '/men-tee-stripe-knit.png': 'https://res.cloudinary.com/qrhgjdrs/image/upload/v1789393782/men-tee-stripe-knit_ms8ipb.png',
  'men-tee-tokyo-racing.png': 'https://res.cloudinary.com/qrhgjdrs/image/upload/v1789393781/men-tee-tokyo-racing_ygxqir.png',
  '/men-tee-tokyo-racing.png': 'https://res.cloudinary.com/qrhgjdrs/image/upload/v1789393781/men-tee-tokyo-racing_ygxqir.png',
  'men-tee-ivory-pleated-polo.png': 'https://res.cloudinary.com/qrhgjdrs/image/upload/v1789393781/men-tee-ivory-pleated-polo_heoxp9.png',
  '/men-tee-ivory-pleated-polo.png': 'https://res.cloudinary.com/qrhgjdrs/image/upload/v1789393781/men-tee-ivory-pleated-polo_heoxp9.png',
  'men-tees-hanger-hero.jpg': 'https://res.cloudinary.com/qrhgjdrs/image/upload/v1789393779/men-tees-hanger-hero_q76qr8.jpg',
  '/men-tees-hanger-hero.jpg': 'https://res.cloudinary.com/qrhgjdrs/image/upload/v1789393779/men-tees-hanger-hero_q76qr8.jpg',
  'men-pants-acid-denim.png': 'https://res.cloudinary.com/qrhgjdrs/image/upload/v1789393779/men-pants-acid-denim_jenaqq.png',
  '/men-pants-acid-denim.png': 'https://res.cloudinary.com/qrhgjdrs/image/upload/v1789393779/men-pants-acid-denim_jenaqq.png',
  'men-tee-noir-zip-polo.png': 'https://res.cloudinary.com/qrhgjdrs/image/upload/v1789393779/men-tee-noir-zip-polo_szazic.png',
  '/men-tee-noir-zip-polo.png': 'https://res.cloudinary.com/qrhgjdrs/image/upload/v1789393779/men-tee-noir-zip-polo_szazic.png',
  'men-pants-olive-cargo.png': 'https://res.cloudinary.com/qrhgjdrs/image/upload/v1789393778/men-pants-olive-cargo_bnzfat.png',
  '/men-pants-olive-cargo.png': 'https://res.cloudinary.com/qrhgjdrs/image/upload/v1789393778/men-pants-olive-cargo_bnzfat.png',
  'men-pants-noir-pleated.png': 'https://res.cloudinary.com/qrhgjdrs/image/upload/v1789393778/men-pants-noir-pleated_uoyv0z.png',
  '/men-pants-noir-pleated.png': 'https://res.cloudinary.com/qrhgjdrs/image/upload/v1789393778/men-pants-noir-pleated_uoyv0z.png',
  'men-pants-white-skate.png': 'https://res.cloudinary.com/qrhgjdrs/image/upload/v1789393777/men-pants-white-skate_fxvzkq.png',
  '/men-pants-white-skate.png': 'https://res.cloudinary.com/qrhgjdrs/image/upload/v1789393777/men-pants-white-skate_fxvzkq.png',
  'men-pants-hanger-hero.jpg': 'https://res.cloudinary.com/qrhgjdrs/image/upload/v1789393777/men-pants-hanger-hero_z0g0oo.jpg',
  '/men-pants-hanger-hero.jpg': 'https://res.cloudinary.com/qrhgjdrs/image/upload/v1789393777/men-pants-hanger-hero_z0g0oo.jpg',
  'men-oatmeal-cutout.png': 'https://res.cloudinary.com/qrhgjdrs/image/upload/v1789393775/men-oatmeal-cutout_xtfxwq.png',
  '/men-oatmeal-cutout.png': 'https://res.cloudinary.com/qrhgjdrs/image/upload/v1789393775/men-oatmeal-cutout_xtfxwq.png',
  'men-combo-plaid-linen-black.png': 'https://res.cloudinary.com/qrhgjdrs/image/upload/v1789393776/men-combo-plaid-linen-black_olelys.png',
  '/men-combo-plaid-linen-black.png': 'https://res.cloudinary.com/qrhgjdrs/image/upload/v1789393776/men-combo-plaid-linen-black_olelys.png',
  'men-pants-cyber-jogger.png': 'https://res.cloudinary.com/qrhgjdrs/image/upload/v1789393776/men-pants-cyber-jogger_bmpw4k.png',
  '/men-pants-cyber-jogger.png': 'https://res.cloudinary.com/qrhgjdrs/image/upload/v1789393776/men-pants-cyber-jogger_bmpw4k.png',

  'men-navy-linen-cutout.png': 'https://res.cloudinary.com/qrhgjdrs/image/upload/v1789393776/men-navy-linen-cutout_z2irht.png',
  '/men-navy-linen-cutout.png': 'https://res.cloudinary.com/qrhgjdrs/image/upload/v1789393776/men-navy-linen-cutout_z2irht.png',
  'men-navy-contrast-cutout.png': 'https://res.cloudinary.com/qrhgjdrs/image/upload/v1789393774/men-navy-contrast-cutout_tvt367.png',
  '/men-navy-contrast-cutout.png': 'https://res.cloudinary.com/qrhgjdrs/image/upload/v1789393774/men-navy-contrast-cutout_tvt367.png',
  'men-combos-hanger-hero.jpg': 'https://res.cloudinary.com/qrhgjdrs/image/upload/v1789393774/men-combos-hanger-hero_kvjlz4.jpg',
  '/men-combos-hanger-hero.jpg': 'https://res.cloudinary.com/qrhgjdrs/image/upload/v1789393774/men-combos-hanger-hero_kvjlz4.jpg',
  'men-ecru-polo-cutout.png': 'https://res.cloudinary.com/qrhgjdrs/image/upload/v1789393774/men-ecru-polo-cutout_pfoen8.png',
  '/men-ecru-polo-cutout.png': 'https://res.cloudinary.com/qrhgjdrs/image/upload/v1789393774/men-ecru-polo-cutout_pfoen8.png',
  'men-combo-camel-jacket-set.png': 'https://res.cloudinary.com/qrhgjdrs/image/upload/v1789393772/men-combo-camel-jacket-set_yixzvb.png',
  '/men-combo-camel-jacket-set.png': 'https://res.cloudinary.com/qrhgjdrs/image/upload/v1789393772/men-combo-camel-jacket-set_yixzvb.png',
  'men-combo-black-oxford-denim.png': 'https://res.cloudinary.com/qrhgjdrs/image/upload/v1789393772/men-combo-black-oxford-denim_lt7tpv.png',
  '/men-combo-black-oxford-denim.png': 'https://res.cloudinary.com/qrhgjdrs/image/upload/v1789393772/men-combo-black-oxford-denim_lt7tpv.png',
  'men-combo-pinstripe-charcoal.png': 'https://res.cloudinary.com/qrhgjdrs/image/upload/v1789393772/men-combo-pinstripe-charcoal_nnd119.png',
  '/men-combo-pinstripe-charcoal.png': 'https://res.cloudinary.com/qrhgjdrs/image/upload/v1789393772/men-combo-pinstripe-charcoal_nnd119.png',
  'men-combo-graphic-23-streetwear.png': 'https://res.cloudinary.com/qrhgjdrs/image/upload/v1789393772/men-combo-graphic-23-streetwear_w3wae9.png',
  '/men-combo-graphic-23-streetwear.png': 'https://res.cloudinary.com/qrhgjdrs/image/upload/v1789393772/men-combo-graphic-23-streetwear_w3wae9.png',
  'lemon-linen-cutout.png': 'https://res.cloudinary.com/qrhgjdrs/image/upload/v1789393771/lemon-linen-cutout_taimes.png',
  '/lemon-linen-cutout.png': 'https://res.cloudinary.com/qrhgjdrs/image/upload/v1789393771/lemon-linen-cutout_taimes.png',
  'men-black-zip-polo-cutout.png': 'https://res.cloudinary.com/qrhgjdrs/image/upload/v1789393770/men-black-zip-polo-cutout_bel8mx.png',
  '/men-black-zip-polo-cutout.png': 'https://res.cloudinary.com/qrhgjdrs/image/upload/v1789393770/men-black-zip-polo-cutout_bel8mx.png',
  'men-archive-mocha-cutout.png': 'https://res.cloudinary.com/qrhgjdrs/image/upload/v1789393768/men-archive-mocha-cutout_d4aze5.png',
  '/men-archive-mocha-cutout.png': 'https://res.cloudinary.com/qrhgjdrs/image/upload/v1789393768/men-archive-mocha-cutout_d4aze5.png',
  'lemon-linen-model.png': 'https://res.cloudinary.com/qrhgjdrs/image/upload/v1789393767/lemon-linen-model_nmwou9.png',
  '/lemon-linen-model.png': 'https://res.cloudinary.com/qrhgjdrs/image/upload/v1789393767/lemon-linen-model_nmwou9.png',
  'floral-kurti-model.png': 'https://res.cloudinary.com/qrhgjdrs/image/upload/v1789393762/floral-kurti-model_cs7lwi.png',
  '/floral-kurti-model.png': 'https://res.cloudinary.com/qrhgjdrs/image/upload/v1789393762/floral-kurti-model_cs7lwi.png',
  'hanger-shirts-hero-new.jpg': 'https://res.cloudinary.com/qrhgjdrs/image/upload/v1789393762/hanger-shirts-hero-new_fqk0ca.jpg',
  '/hanger-shirts-hero-new.jpg': 'https://res.cloudinary.com/qrhgjdrs/image/upload/v1789393762/hanger-shirts-hero-new_fqk0ca.jpg',
  'fighter-kenji.png': 'https://res.cloudinary.com/qrhgjdrs/image/upload/v1789393753/fighter-kenji_pufr1a.png',
  '/fighter-kenji.png': 'https://res.cloudinary.com/qrhgjdrs/image/upload/v1789393753/fighter-kenji_pufr1a.png',
  'floral-kurti-cutout.png': 'https://res.cloudinary.com/qrhgjdrs/image/upload/v1789393756/floral-kurti-cutout_kq8ewp.png',
  '/floral-kurti-cutout.png': 'https://res.cloudinary.com/qrhgjdrs/image/upload/v1789393756/floral-kurti-cutout_kq8ewp.png',

  'couple-mocha-linen.png': 'https://res.cloudinary.com/qrhgjdrs/image/upload/v1789393752/couple-mocha-linen_q7b1gk.png',
  '/couple-mocha-linen.png': 'https://res.cloudinary.com/qrhgjdrs/image/upload/v1789393752/couple-mocha-linen_q7b1gk.png',
  'couple-indigo-festive.png': 'https://res.cloudinary.com/qrhgjdrs/image/upload/v1789393751/couple-indigo-festive_wirzr7.png',
  '/couple-indigo-festive.png': 'https://res.cloudinary.com/qrhgjdrs/image/upload/v1789393751/couple-indigo-festive_wirzr7.png',
  'couple-sky-stripe.png': 'https://res.cloudinary.com/qrhgjdrs/image/upload/v1789393751/couple-sky-stripe_xffsj2.png',
  '/couple-sky-stripe.png': 'https://res.cloudinary.com/qrhgjdrs/image/upload/v1789393751/couple-sky-stripe_xffsj2.png',
  'couple-burgundy-cord.png': 'https://res.cloudinary.com/qrhgjdrs/image/upload/v1789393749/couple-burgundy-cord_rqepmt.png',
  '/couple-burgundy-cord.png': 'https://res.cloudinary.com/qrhgjdrs/image/upload/v1789393749/couple-burgundy-cord_rqepmt.png',
  'couple-noir-linen.png': 'https://res.cloudinary.com/qrhgjdrs/image/upload/v1789393750/couple-noir-linen_jhoevy.png',
  '/couple-noir-linen.png': 'https://res.cloudinary.com/qrhgjdrs/image/upload/v1789393750/couple-noir-linen_jhoevy.png',
  'couple-hanger-hero.jpg': 'https://res.cloudinary.com/qrhgjdrs/image/upload/v1789393749/couple-hanger-hero_i1lpgf.jpg',
  '/couple-hanger-hero.jpg': 'https://res.cloudinary.com/qrhgjdrs/image/upload/v1789393749/couple-hanger-hero_i1lpgf.jpg',
};

export function getAssetUrl(path) {
  if (!path) return '';
  if (path.startsWith('http://') || path.startsWith('https://')) return path;
  if (CLOUDINARY_ASSETS[path]) return CLOUDINARY_ASSETS[path];
  
  const basename = path.split('/').pop();
  if (CLOUDINARY_ASSETS[basename]) return CLOUDINARY_ASSETS[basename];
  if (CLOUDINARY_ASSETS['/' + basename]) return CLOUDINARY_ASSETS['/' + basename];

  return path;
}
